export type AllowedType = 'P' | 'L' | 'P/L'

export interface CatalogCourse {
  id: string
  code: string
  area: number
  areaName: string
  name: string
  defaultHours: number
  allowedTypes: AllowedType
  target: string
  abstract: string
}

export const AREA_NAMES: Record<number, string> = {
  1: 'Comprendere l\'AI',
  2: 'Progettare didattica con l\'AI',
  3: 'Sviluppare competenze e rinnovare le discipline con l\'AI',
  4: 'Pedagogia algoritmica',
  5: 'Gli strumenti',
}

export const AREA_SUBTITLES: Record<number, string> = {
  1: 'AI Literacy & Epistemology',
  2: 'AI-Augmented Learning Design',
  3: 'Learning with AI',
  4: 'Algorithmic Pedagogy',
  5: 'Piattaforme e applicativi FEM',
}

export const CATALOG: CatalogCourse[] = [
  // === AREA 1: Comprendere l'AI ===
  {
    id: 'AI-FEM1-01',
    code: 'AI-FEM1-01',
    area: 1,
    areaName: AREA_NAMES[1],
    name: 'AI Act e istruzione: implicazioni giuridiche dell\'intelligenza artificiale per scuole',
    defaultHours: 10,
    allowedTypes: 'P',
    target: 'Personale scolastico / Docenti',
    abstract: 'Il corso approfondisce le implicazioni giuridiche dell\'uso dell\'intelligenza artificiale nella didattica, con particolare attenzione al ruolo dei docenti e al quadro introdotto dall\'AI Act europeo. Attraverso esempi e casi d\'uso, i partecipanti analizzeranno rischi, responsabilità e limiti dell\'AI in ambito educativo, con focus su trasparenza, supervisione umana e tutela degli studenti.',
  },
  {
    id: 'AI-FEM1-02',
    code: 'AI-FEM1-02',
    area: 1,
    areaName: AREA_NAMES[1],
    name: 'AI per l\'organizzazione scolastica: migliorare processi e servizi',
    defaultHours: 10,
    allowedTypes: 'P',
    target: 'Personale scolastico / Docenti',
    abstract: 'Come può l\'intelligenza artificiale migliorare concretamente l\'organizzazione scolastica? Questo corso guida dirigenti e staff nella riprogettazione di processi e servizi attraverso l\'AI. Partendo da casi reali, i partecipanti lavoreranno su flussi esistenti per analizzarli, semplificarli e potenziarli con strumenti di AI.',
  },

  // === AREA 2: Progettare didattica con l'AI ===
  {
    id: 'AI-FEM2-01',
    code: 'AI-FEM2-01',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'AI per la Didattica — Base',
    defaultHours: 10,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Il corso introduce i docenti all\'uso dell\'intelligenza artificiale come supporto alla progettazione e alla gestione della didattica. I partecipanti imparano a utilizzare le principali piattaforme di AI generativa per ideare attività, costruire materiali, progettare lezioni e supportare la valutazione.',
  },
  {
    id: 'AI-FEM2-02',
    code: 'AI-FEM2-02',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'AI per la Didattica — Avanzato',
    defaultHours: 10,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Il corso è pensato per docenti che vogliono andare oltre l\'uso base dell\'intelligenza artificiale e integrarla in modo strutturato nella propria pratica didattica. Il percorso copre l\'intera filiera delle competenze AI applicate alla didattica: dalla comprensione dei LLM alle tecniche avanzate di prompt engineering, dalla generazione di contenuti allo sviluppo di agenti e assistenti virtuali.',
  },
  {
    id: 'AI-FEM2-03',
    code: 'AI-FEM2-03',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'Innovare la didattica con Canva AI',
    defaultHours: 6,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso accompagna i docenti nell\'utilizzo di Canva AI come strumento per progettare, visualizzare e innovare esperienze di apprendimento. Attraverso approcci come il Design Thinking e il Learner Journey, i docenti utilizzeranno Canva come ambiente di co-progettazione aumentata.',
  },
  {
    id: 'AI-FEM2-04',
    code: 'AI-FEM2-04',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'AI e UDL: progettare didattica inclusiva con l\'intelligenza artificiale',
    defaultHours: 10,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso introduce i docenti alla progettazione di esperienze di apprendimento inclusive attraverso l\'integrazione tra Universal Design for Learning (UDL) e intelligenza artificiale. L\'AI viene esplorata come leva per ampliare le possibilità di accesso, partecipazione ed espressione degli studenti.',
  },
  {
    id: 'AI-FEM2-05',
    code: 'AI-FEM2-05',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'IA come strumento per la trasformazione di materiale didattico universale',
    defaultHours: 6,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso introduce i partecipanti all\'uso pratico dell\'intelligenza artificiale per trasformare contenuti testuali, visivi e multimediali in materiali accessibili, adattabili e fruibili da una pluralità di utenti con bisogni differenti.',
  },
  {
    id: 'AI-FEM2-06',
    code: 'AI-FEM2-06',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'AI e Neuroscienze: progettazione didattica efficace',
    defaultHours: 10,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Il corso introduce i docenti ai principali meccanismi cognitivi che influenzano l\'apprendimento e mostra come tradurli in scelte didattiche concrete, utilizzando l\'intelligenza artificiale come supporto alla progettazione e alla personalizzazione degli apprendimenti.',
  },
  {
    id: 'AI-FEM2-07',
    code: 'AI-FEM2-07',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'Progettare con l\'IA: dall\'idea alla pratica con il design thinking',
    defaultHours: 8,
    allowedTypes: 'P/L',
    target: 'Docenti / Personale scolastico',
    abstract: 'Il corso mostra come l\'intelligenza artificiale possa potenziare i processi di progettazione in ambito educativo. Attraverso laboratori pratici, i partecipanti apprenderanno come affiancare l\'AI nelle fasi chiave del Design Thinking.',
  },
  {
    id: 'AI-FEM2-08',
    code: 'AI-FEM2-08',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'Valutare con l\'AI: strumenti e criteri per una valutazione formativa, trasparente e sostenibile',
    defaultHours: 10,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Questo corso esplora come utilizzare strumenti di AI per supportare processi valutativi più tempestivi, personalizzati e orientati alla crescita. I partecipanti impareranno a utilizzare l\'AI per feedback formativo, progettare rubriche e prompt valutativi, riconoscere limiti e bias nella valutazione automatica.',
  },
  {
    id: 'AI-FEM2-09',
    code: 'AI-FEM2-09',
    area: 2,
    areaName: AREA_NAMES[2],
    name: 'AI Safari: scegliere e navigare tecnologie AI per la formazione',
    defaultHours: 10,
    allowedTypes: 'P',
    target: 'Docenti / Personale scolastico',
    abstract: 'Questo corso guida i partecipanti nella valutazione e selezione di tecnologie AI applicate alla formazione attraverso un approccio di design dell\'esperienza: analisi dei bisogni, definizione dei criteri di scelta, mappatura delle opzioni e verifica della coerenza tra strumento, obiettivo didattico e contesto d\'uso.',
  },

  // === AREA 3: Sviluppare competenze e rinnovare le discipline con l'AI ===
  {
    id: 'AI-FEM3-01',
    code: 'AI-FEM3-01',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'IA e discipline umanistiche: pratiche, metodi, orientamento',
    defaultHours: 8,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Il corso guida i docenti delle discipline umanistiche in un percorso di riflessione e sperimentazione sull\'uso formativo dell\'intelligenza artificiale generativa e semantica, esplorando come l\'AI possa supportare il lavoro critico sui testi, la costruzione argomentativa e il confronto tra fonti.',
  },
  {
    id: 'AI-FEM3-02',
    code: 'AI-FEM3-02',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'Insegnare la scrittura con l\'IA',
    defaultHours: 8,
    allowedTypes: 'P/L',
    target: 'Docenti / Studenti',
    abstract: 'Il percorso guida i docenti in un\'esperienza pratica sull\'uso dell\'intelligenza artificiale come strumento di supporto al processo di scrittura, accompagnando studenti nelle fasi di ideazione, stesura e revisione del testo.',
  },
  {
    id: 'AI-FEM3-03',
    code: 'AI-FEM3-03',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'Me, Myself and AI: come sfruttare l\'IA conversazionale per insegnare l\'inglese',
    defaultHours: 6,
    allowedTypes: 'P/L',
    target: 'Docenti / Studenti',
    abstract: 'Il corso esplora il potenziale dell\'intelligenza artificiale conversazionale nell\'insegnamento dell\'inglese come L2, offrendo strumenti teorici e operativi per integrare queste tecnologie nella pratica didattica.',
  },
  {
    id: 'AI-FEM3-04',
    code: 'AI-FEM3-04',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'AI e alfabetizzazione visiva digitale: creare, leggere e interpretare le immagini nel XXI secolo',
    defaultHours: 6,
    allowedTypes: 'P/L',
    target: 'Docenti / Studenti',
    abstract: 'Il corso sviluppa competenze di alfabetizzazione visiva attraverso l\'integrazione tra storia dell\'arte, intelligenza artificiale e tecnologie digitali emergenti.',
  },
  {
    id: 'AI-FEM3-05',
    code: 'AI-FEM3-05',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'AI e media education: educare al pensiero critico nell\'era degli algoritmi',
    defaultHours: 8,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il percorso propone un uso educativo dell\'intelligenza artificiale come occasione per sviluppare pensiero critico, consapevolezza digitale e autonomia negli studenti, seguendo le tre traiettorie della Media Education.',
  },
  {
    id: 'AI-FEM3-06',
    code: 'AI-FEM3-06',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'Insegnare il pensiero critico al tempo dell\'IA',
    defaultHours: 4,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Questo corso breve introduce i partecipanti ai fondamenti del pensiero critico e alle strategie più efficaci per promuoverlo nella didattica. I docenti approfondiranno bias cognitivi, dubbio produttivo, analisi delle fonti e routine di pensiero visibile.',
  },
  {
    id: 'AI-FEM3-07',
    code: 'AI-FEM3-07',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'AI & pensiero computazionale per la scuola del primo ciclo',
    defaultHours: 8,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso accompagna i docenti nell\'uso didattico del pensiero computazionale e dell\'intelligenza artificiale, integrando metodologie attive come Problem Based Learning e Project Based Learning con strumenti come Scratch, Code.org, Minecraft Education.',
  },
  {
    id: 'AI-FEM3-08',
    code: 'AI-FEM3-08',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'AI e Metodo di Studio',
    defaultHours: 8,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Il corso fornisce conoscenze teoriche e strumenti operativi per l\'integrazione consapevole dell\'intelligenza artificiale nei processi di apprendimento e nello sviluppo di un metodo di studio efficace, autonomo e personalizzato.',
  },
  {
    id: 'AI-FEM3-09',
    code: 'AI-FEM3-09',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'School of Data & AI',
    defaultHours: 8,
    allowedTypes: 'L',
    target: 'Docenti',
    abstract: 'Il percorso accompagna docenti e classi alla scoperta della data science e dell\'intelligenza artificiale, offrendo basi teoriche e pratiche per integrare strumenti di analisi dati e AI nella didattica.',
  },
  {
    id: 'AI-FEM3-10',
    code: 'AI-FEM3-10',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'GenAI per l\'analisi dei dati',
    defaultHours: 6,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso insegna a utilizzare l\'intelligenza artificiale generativa per trasformare i dati di apprendimento in decisioni didattiche strategiche e fondate su evidenze.',
  },
  {
    id: 'AI-FEM3-11',
    code: 'AI-FEM3-11',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'Fonti affidabili, dati e AI per contrastare la disinformazione in campo ambientale',
    defaultHours: 6,
    allowedTypes: 'L',
    target: 'Docenti',
    abstract: 'Questo laboratorio sviluppa competenze per leggere, analizzare e comunicare informazioni sulla sostenibilità in modo rigoroso, contrastando la disinformazione in ambito ambientale.',
  },
  {
    id: 'AI-FEM3-12',
    code: 'AI-FEM3-12',
    area: 3,
    areaName: AREA_NAMES[3],
    name: 'STEM for Green: AI per insegnare le scienze e la sostenibilità',
    defaultHours: 6,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Percorso che offre una cassetta degli attrezzi metodologica e tecnologica avanzata per esplorare i temi ambientali attraverso simulazioni, sensori, mappe digitali, analisi dati e intelligenza artificiale applicata all\'apprendimento.',
  },

  // === AREA 4: Pedagogia algoritmica ===
  {
    id: 'AI-FEM4-01',
    code: 'AI-FEM4-01',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'PromptLab: sfide di prompt design per progettare e allenare un\'AI con gli studenti',
    defaultHours: 10,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso presenta e sperimenta il metodo Prompt Lab, un approccio innovativo attraverso il quale gli studenti assumono un ruolo attivo nell\'allenamento dell\'intelligenza artificiale, insegnandole a riconoscere pattern e fenomeni specifici.',
  },
  {
    id: 'AI-FEM4-02',
    code: 'AI-FEM4-02',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'Costruire attività scientifiche con Python e l\'AI',
    defaultHours: 8,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso propone un percorso attivo di apprendimento di Python come linguaggio per l\'analisi dei dati, applicato a sfide progettuali legate a problemi ambientali urbani, integrando l\'intelligenza artificiale.',
  },
  {
    id: 'AI-FEM4-03',
    code: 'AI-FEM4-03',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'Progetta il tuo AI Tutor: agenti conversazionali per l\'apprendimento personalizzato',
    defaultHours: 10,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Questo corso accompagna i docenti nella progettazione e sperimentazione di AI tutor su misura per le proprie classi, imparando a progettare il comportamento di un agente, scrivere prompt strutturati e creare prototipi funzionanti.',
  },
  {
    id: 'AI-FEM4-04',
    code: 'AI-FEM4-04',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'Vibe coding per la didattica: ambienti immersivi, simulazioni e role-playing con agenti intelligenti',
    defaultHours: 10,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Il corso esplora il paradigma del vibe coding applicato all\'educazione: un approccio in cui l\'AI diventa co-designer di ambienti, simulazioni e strumenti didattici, utilizzando piattaforme come WebSim, CoSpaces Edu e Lovable.',
  },
  {
    id: 'AI-FEM4-05',
    code: 'AI-FEM4-05',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'Creare il tuo assistente didattico con l\'intelligenza artificiale',
    defaultHours: 6,
    allowedTypes: 'P',
    target: 'Docenti',
    abstract: 'Percorso pratico e guidato per ideare e costruire un assistente digitale personalizzato, utile per la progettazione di lezioni, la pianificazione di percorsi formativi e la creazione di materiali didattici mirati.',
  },
  {
    id: 'AI-FEM4-06',
    code: 'AI-FEM4-06',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'Progettare ambienti immersivi basati sul gioco con Delightex AI',
    defaultHours: 10,
    allowedTypes: 'P/L',
    target: 'Docenti',
    abstract: 'Laboratorio pratico per progettare ambienti interattivi tridimensionali con personaggi che rispondono in modo intelligente alle azioni degli studenti, usando le funzioni AI di Delightex.',
  },
  {
    id: 'AI-FEM4-07',
    code: 'AI-FEM4-07',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'Creare sistemi laboratoriali con Google AI Studio',
    defaultHours: 10,
    allowedTypes: 'P/L',
    target: 'Docenti / Studenti',
    abstract: 'Il corso insegna a usare Google AI Studio non per conversare, ma per costruire. I partecipanti acquisiranno un metodo per governare la complessità dell\'informazione nell\'era dell\'AI.',
  },
  {
    id: 'AI-FEM4-08',
    code: 'AI-FEM4-08',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'Prompt Lab: Imparare l\'inglese con l\'AI (Studenti)',
    defaultHours: 10,
    allowedTypes: 'L',
    target: 'Studenti',
    abstract: 'Percorso laboratoriale dedicato all\'uso dell\'intelligenza artificiale nella didattica dell\'inglese, con focus sull\'analisi dei phrasal verbs attraverso corpora linguistici, prompt engineering e piattaforme conversazionali.',
  },
  {
    id: 'AI-FEM4-09',
    code: 'AI-FEM4-09',
    area: 4,
    areaName: AREA_NAMES[4],
    name: 'School of Data & AI (Studenti)',
    defaultHours: 10,
    allowedTypes: 'L',
    target: 'Studenti',
    abstract: 'Il corso introduce studenti e studentesse alla data science come strumento per leggere, analizzare e comunicare i dati in modo consapevole, sviluppando competenze utili anche per comprendere il funzionamento e l\'impatto dell\'intelligenza artificiale.',
  },

  // === AREA 5: Gli strumenti ===
  {
    id: 'AI-FEM5-01',
    code: 'AI-FEM5-01',
    area: 5,
    areaName: AREA_NAMES[5],
    name: 'AI for Learning: la piattaforma pedagogicamente intelligente per la progettazione didattica',
    defaultHours: 10,
    allowedTypes: 'L',
    target: 'Docenti',
    abstract: 'Piattaforma FEM proprietaria per la progettazione didattica con intelligenza artificiale, validata pedagogicamente e testata sul campo.',
  },
  {
    id: 'AI-FEM5-02',
    code: 'AI-FEM5-02',
    area: 5,
    areaName: AREA_NAMES[5],
    name: 'LINDA: intelligenza artificiale a supporto della comprensione del testo, della lettura e dell\'analisi testuale',
    defaultHours: 10,
    allowedTypes: 'P/L',
    target: 'Docenti / Studenti',
    abstract: 'Piattaforma FEM proprietaria di AI a supporto della comprensione del testo, della lettura e dell\'analisi testuale.',
  },
]

export function getCoursesByArea(area: number): CatalogCourse[] {
  return CATALOG.filter(c => c.area === area)
}
